name: Workflow Sync
on:
  repository_dispatch:
    types: [sync-workflow]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: main

      - name: Checkout workflows repo
        uses: actions/checkout@v2
        with:
          repository: cferri-gr8/github-workflows
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: workflows

      - name: Copy workflow
        run: cp workflows/${{ github.event.client_payload.workflow }} main/.github/workflows/ci.yml

      - name: Commit workflow
        run: |
          cd main
          git add .github/workflows/ci.yml
          git config --global user.name github-actions
          git diff --staged --quiet || git commit -m 'Update from ${{ github.event.client_payload.repository }} CICD ${{ github.event.client_payload.sha }}'
          git push https://cferri-gr8:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
